-- Database backup generated by App\Services\DatabaseBackupService
-- Generated at: 2026-05-24 12:18:29
-- Connection driver: sqlsrv
-- Database name: endorse
SET NOCOUNT ON;

-- ------------------------------------------------------------------
-- Table: [dbo].[backup_logs]
IF OBJECT_ID(N'dbo.backup_logs', N'U') IS NOT NULL DROP TABLE [dbo].[backup_logs];
CREATE TABLE [dbo].[backup_logs] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [triggered_by] bigint NULL,
    [trigger_type] nvarchar(20) DEFAULT ('manual') NOT NULL,
    [status] nvarchar(20) DEFAULT ('running') NOT NULL,
    [database_driver] nvarchar(20) NULL,
    [timezone] nvarchar(64) NULL,
    [scheduled_for] datetime NULL,
    [started_at] datetime NOT NULL,
    [finished_at] datetime NULL,
    [file_name] nvarchar(255) NULL,
    [file_path] nvarchar(255) NULL,
    [file_size_bytes] bigint NULL,
    [message] nvarchar(max) NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__backup_l__3213E83F90E553E5] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[backup_logs] ON;
INSERT INTO [dbo].[backup_logs] ([id], [triggered_by], [trigger_type], [status], [database_driver], [timezone], [scheduled_for], [started_at], [finished_at], [file_name], [file_path], [file_size_bytes], [message], [created_at], [updated_at]) VALUES
(1, 3, N'manual', N'success', N'sqlsrv', N'Asia/Jakarta', NULL, N'2026-05-09 03:36:49.213', N'2026-05-09 03:36:49.737', N'endorse_tracker_20260509_033649.sql', N'/var/www/nalehanan/endorse/storage/app/backups/database/endorse_tracker_20260509_033649.sql', 77315, N'Backup selesai.', N'2026-05-09 03:36:49.213', N'2026-05-09 03:36:49.737'),
(2, 3, N'manual', N'success', N'sqlsrv', N'Asia/Jakarta', NULL, N'2026-05-10 05:01:05.623', N'2026-05-10 05:01:06.437', N'endorse_tracker_20260510_050106.sql', N'/var/www/nalehanan/endorse/storage/app/backups/database/endorse_tracker_20260510_050106.sql', 81813, N'Backup selesai.', N'2026-05-10 05:01:05.623', N'2026-05-10 05:01:06.437'),
(3, 3, N'manual', N'success', N'sqlsrv', N'Asia/Jakarta', NULL, N'2026-05-17 12:28:55.817', N'2026-05-17 12:28:56.717', N'endorse_tracker_20260517_122856.sql', N'/var/www/nalehanan/endorse/storage/app/backups/database/endorse_tracker_20260517_122856.sql', 90646, N'Backup selesai. 2 file backup lama dibersihkan.', N'2026-05-17 12:28:55.817', N'2026-05-17 12:28:56.717'),
(4, 3, N'manual', N'success', N'sqlsrv', N'Asia/Jakarta', NULL, N'2026-05-22 15:14:42.943', N'2026-05-22 15:14:43.480', N'endorse_tracker_20260522_151443.sql', N'/var/www/nalehanan/endorse/storage/app/backups/database/endorse_tracker_20260522_151443.sql', 94197, N'Backup selesai.', N'2026-05-22 15:14:42.943', N'2026-05-22 15:14:43.483'),
(5, 3, N'manual', N'running', N'sqlsrv', N'Asia/Jakarta', NULL, N'2026-05-24 12:18:29.000', NULL, NULL, NULL, NULL, N'Backup dimulai.', N'2026-05-24 12:18:29.000', N'2026-05-24 12:18:29.000');
SET IDENTITY_INSERT [dbo].[backup_logs] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[backup_settings]
IF OBJECT_ID(N'dbo.backup_settings', N'U') IS NOT NULL DROP TABLE [dbo].[backup_settings];
CREATE TABLE [dbo].[backup_settings] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [enabled] bit DEFAULT ('0') NOT NULL,
    [timezone] nvarchar(64) DEFAULT ('Asia/Jakarta') NOT NULL,
    [run_time] nvarchar(5) DEFAULT ('01:00') NOT NULL,
    [run_days] nvarchar(max) NULL,
    [start_date] date NULL,
    [end_date] date NULL,
    [keep_days] smallint DEFAULT ('7') NOT NULL,
    [updated_by] bigint NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__backup_s__3213E83F8E30CBB4] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[backup_settings] ON;
INSERT INTO [dbo].[backup_settings] ([id], [enabled], [timezone], [run_time], [run_days], [start_date], [end_date], [keep_days], [updated_by], [created_at], [updated_at]) VALUES
(1, 0, N'Asia/Jakarta', N'01:00', N'["mon","tue","wed","thu","fri","sat","sun"]', NULL, NULL, 7, NULL, N'2026-05-09 03:36:29.723', N'2026-05-09 03:36:29.723');
SET IDENTITY_INSERT [dbo].[backup_settings] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[cache]
IF OBJECT_ID(N'dbo.cache', N'U') IS NOT NULL DROP TABLE [dbo].[cache];
CREATE TABLE [dbo].[cache] (
    [key] nvarchar(255) NOT NULL,
    [value] nvarchar(max) NOT NULL,
    [expiration] int NOT NULL,
    CONSTRAINT [cache_key_primary] PRIMARY KEY ([key])
);

-- ------------------------------------------------------------------
-- Table: [dbo].[cache_locks]
IF OBJECT_ID(N'dbo.cache_locks', N'U') IS NOT NULL DROP TABLE [dbo].[cache_locks];
CREATE TABLE [dbo].[cache_locks] (
    [key] nvarchar(255) NOT NULL,
    [owner] nvarchar(255) NOT NULL,
    [expiration] int NOT NULL,
    CONSTRAINT [cache_locks_key_primary] PRIMARY KEY ([key])
);

-- ------------------------------------------------------------------
-- Table: [dbo].[endorsement_activities]
IF OBJECT_ID(N'dbo.endorsement_activities', N'U') IS NOT NULL DROP TABLE [dbo].[endorsement_activities];
CREATE TABLE [dbo].[endorsement_activities] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [endorsement_id] bigint NULL,
    [user_id] bigint NULL,
    [action] nvarchar(100) NOT NULL,
    [meta] nvarchar(max) NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__endorsem__3213E83FBDD2F297] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[endorsement_activities] ON;
INSERT INTO [dbo].[endorsement_activities] ([id], [endorsement_id], [user_id], [action], [meta], [created_at], [updated_at]) VALUES
(1, 18, 3, N'update', N'{"status":"selesai","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"35000.00","to":"22000.00"}}}', N'2026-04-26 12:42:26.033', N'2026-04-26 12:42:26.033'),
(2, 16, 3, N'update', N'{"status":"selesai","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"35000.00","to":"29000.00"}}}', N'2026-04-26 12:42:42.420', N'2026-04-26 12:42:42.420'),
(3, 9, 3, N'update', N'{"status":"selesai","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"140000.00","to":"275000.00"}}}', N'2026-04-26 12:43:24.793', N'2026-04-26 12:43:24.793'),
(4, 21, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-26 12:54:34.253', N'2026-04-26 12:54:34.253'),
(5, 43, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-04-26 13:01:23.647', N'2026-04-26 13:01:23.647'),
(6, 44, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-04-26 13:04:20.153', N'2026-04-26 13:04:20.153'),
(7, 45, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-04-26 13:07:56.070', N'2026-04-26 13:07:56.070'),
(8, 34, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-26 13:10:52.597', N'2026-04-26 13:10:52.597'),
(9, 46, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-04-26 13:15:39.377', N'2026-04-26 13:15:39.377'),
(10, 47, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-04-26 13:17:21.130', N'2026-04-26 13:17:21.130'),
(11, 30, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-26 13:18:06.577', N'2026-04-26 13:18:06.577'),
(12, 40, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-26 13:18:25.083', N'2026-04-26 13:18:25.083'),
(13, 22, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-26 13:21:22.760', N'2026-04-26 13:21:22.760'),
(14, 6, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-26 13:22:21.917', N'2026-04-26 13:22:21.917'),
(15, 28, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"220000.00","to":"180000.00"}}}', N'2026-04-26 13:29:06.890', N'2026-04-26 13:29:06.890'),
(16, 28, 3, N'status_change', N'{"from":"menunggu_payment","to":"menunggu_payment"}', N'2026-04-26 13:31:34.627', N'2026-04-26 13:31:34.627'),
(17, 28, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-26 13:31:40.303', N'2026-04-26 13:31:40.303'),
(18, 31, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-04-27 06:11:37.937', N'2026-04-27 06:11:37.937'),
(19, 8, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["payment_status"],"changes":{"payment_status":{"from":"belum_bayar","to":"lunas"}}}', N'2026-04-28 08:26:08.453', N'2026-04-28 08:26:08.453'),
(20, 8, 3, N'update', N'{"status":"selesai","fields_changed":["status","payment_received_date"],"changes":{"status":{"from":"menunggu_payment","to":"selesai"},"payment_received_date":{"from":null,"to":"2026-04-28T00:00:00.000000Z"}}}', N'2026-04-28 08:26:26.370', N'2026-04-28 08:26:26.370'),
(21, 11, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"95000.00","to":"90000.00"}}}', N'2026-04-28 08:47:05.120', N'2026-04-28 08:47:05.120'),
(22, 48, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-04-28 09:55:13.147', N'2026-04-28 09:55:13.147'),
(23, 49, 3, N'create', N'{"status":"selesai"}', N'2026-04-28 09:55:59.947', N'2026-04-28 09:55:59.947'),
(24, 11, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-28 15:14:38.840', N'2026-04-28 15:14:38.840'),
(25, 10, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-04-28 15:14:49.370', N'2026-04-28 15:14:49.370'),
(26, 47, 3, N'status_change', N'{"from":"pembelian_produk","to":"pembuatan_draft"}', N'2026-04-28 16:21:27.327', N'2026-04-28 16:21:27.327'),
(27, 46, 3, N'status_change', N'{"from":"pembelian_produk","to":"pembuatan_draft"}', N'2026-04-28 16:21:35.307', N'2026-04-28 16:21:35.307'),
(28, 37, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-28 16:22:15.043', N'2026-04-28 16:22:15.043'),
(29, 24, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-28 16:23:03.057', N'2026-04-28 16:23:03.057'),
(30, 25, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-28 16:23:09.290', N'2026-04-28 16:23:09.290'),
(31, 39, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-04-28 16:23:19.167', N'2026-04-28 16:23:19.167'),
(32, 50, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-04-28 16:33:57.257', N'2026-04-28 16:33:57.257'),
(33, 48, 3, N'status_change', N'{"from":"pembelian_produk","to":"pembuatan_draft"}', N'2026-04-29 04:02:18.797', N'2026-04-29 04:02:18.797'),
(34, 47, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-04-29 07:34:20.773', N'2026-04-29 07:34:20.773'),
(35, 35, 3, N'update', N'{"status":"menunggu_insight","fields_changed":["financial_mode","fee_amount"],"changes":{"financial_mode":{"from":"reimburse_bersama_fee","to":"reimburse_duluan"},"fee_amount":{"from":"120000.00","to":"15000.00"}}}', N'2026-04-30 05:21:35.147', N'2026-04-30 05:21:35.147'),
(36, 13, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-03 06:11:11.290', N'2026-05-03 06:11:11.290'),
(37, 17, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-03 06:11:40.607', N'2026-05-03 06:11:40.607'),
(38, 48, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-04 06:29:14.377', N'2026-05-04 06:29:14.377'),
(39, 50, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-04 06:29:18.067', N'2026-05-04 06:29:18.067'),
(40, 43, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_insight"}', N'2026-05-04 06:29:30.247', N'2026-05-04 06:29:30.247'),
(41, 32, 3, N'status_change', N'{"from":"pembuatan_draft","to":"selesai"}', N'2026-05-04 06:29:39.960', N'2026-05-04 06:29:39.960'),
(42, 35, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-04 06:29:57.147', N'2026-05-04 06:29:57.147'),
(43, 29, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-04 06:34:48.630', N'2026-05-04 06:34:48.630'),
(44, 27, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-04 06:34:51.637', N'2026-05-04 06:34:51.637'),
(45, 44, 3, N'status_change', N'{"from":"pembelian_produk","to":"pembuatan_draft"}', N'2026-05-04 06:36:21.137', N'2026-05-04 06:36:21.137'),
(46, 47, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-04 06:37:12.290', N'2026-05-04 06:37:12.290'),
(10002, 44, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-08 17:40:57.507', N'2026-05-08 17:40:57.507'),
(10003, 46, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_insight"}', N'2026-05-08 17:41:09.767', N'2026-05-08 17:41:09.767'),
(10004, 42, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-08 17:41:18.030', N'2026-05-08 17:41:18.030'),
(10005, 48, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-08 17:41:50.423', N'2026-05-08 17:41:50.423'),
(10006, 47, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-08 17:42:24.933', N'2026-05-08 17:42:24.933'),
(10007, 43, 3, N'status_change', N'{"from":"menunggu_insight","to":"selesai"}', N'2026-05-08 17:42:28.867', N'2026-05-08 17:42:28.867'),
(10008, 38, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-08 17:43:19.627', N'2026-05-08 17:43:19.627'),
(10009, 34, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-08 17:44:35.180', N'2026-05-08 17:44:35.180'),
(10010, 37, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["brand_name"],"changes":{"brand_name":{"from":"MORINAGA CHILKID","to":"CHILKID SIAPAMAU MG"}}}', N'2026-05-09 04:12:47.887', N'2026-05-09 04:12:47.887'),
(10011, 47, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["brand_name"],"changes":{"brand_name":{"from":"MORINAGA CHILKID IG","to":"CHILKID 1,5KG"}}}', N'2026-05-09 04:14:01.727', N'2026-05-09 04:14:01.727'),
(10012, 46, 3, N'update', N'{"status":"menunggu_insight","fields_changed":["brand_name"],"changes":{"brand_name":{"from":"MORINAGA PHP IG","to":"PHP MALIKA"}}}', N'2026-05-09 04:15:25.900', N'2026-05-09 04:15:25.900'),
(10013, 38, 3, N'update', N'{"status":"menunggu_payment","fields_changed":["brand_name"],"changes":{"brand_name":{"from":"MORINAGA P-HP","to":"PHP SURYA"}}}', N'2026-05-09 04:16:23.453', N'2026-05-09 04:16:23.453'),
(10014, 34, 3, N'update', N'{"status":"selesai","fields_changed":["brand_name"],"changes":{"brand_name":{"from":"MORINAGA SOYA","to":"SOYA SIAPAMAU MG"}}}', N'2026-05-09 04:17:10.950', N'2026-05-09 04:17:10.950'),
(10015, 48, 3, N'update', N'{"status":"menunggu_insight","fields_changed":["brand_name","platform"],"changes":{"brand_name":{"from":"Morinaga","to":"CHIL*GO"},"platform":{"from":"tiktok","to":"tiktok_instagram"}}}', N'2026-05-09 04:17:40.400', N'2026-05-09 04:17:40.400'),
(10016, 10002, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-05-09 04:33:38.357', N'2026-05-09 04:33:38.357'),
(10017, 10003, 3, N'create', N'{"status":"deal_masuk"}', N'2026-05-09 04:34:01.933', N'2026-05-09 04:34:01.933'),
(10018, 10003, 3, N'update', N'{"status":"menunggu_draft_ok","fields_changed":["brand_name","campaign_name","status","fee_amount"],"changes":{"brand_name":{"from":"SURYA","to":"CHILKID SURYA"},"campaign_name":{"from":null,"to":"SUFOR"},"status":{"from":"deal_masuk","to":"menunggu_draft_ok"},"fee_amount":{"from":"0.00","to":"200000.00"}}}', N'2026-05-09 04:38:01.293', N'2026-05-09 04:38:01.293'),
(10019, 10004, 3, N'create', N'{"status":"menunggu_insight"}', N'2026-05-09 04:40:02.240', N'2026-05-09 04:40:02.240'),
(10020, 31, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-09 04:53:07.817', N'2026-05-09 04:53:07.817'),
(10021, 30, 3, N'update', N'{"status":"selesai","fields_changed":["status","payment_status","payment_received_date"],"changes":{"status":{"from":"menunggu_payment","to":"selesai"},"payment_status":{"from":"belum_bayar","to":"lunas"},"payment_received_date":{"from":null,"to":"2026-05-09T00:00:00.000000Z"}}}', N'2026-05-09 05:55:07.250', N'2026-05-09 05:55:07.250'),
(10022, 10005, 3, N'create', N'{"status":"menunggu_insight"}', N'2026-05-10 14:35:43.997', N'2026-05-10 14:35:43.997'),
(10023, 10006, 3, N'create', N'{"status":"deal_masuk"}', N'2026-05-10 14:41:05.363', N'2026-05-10 14:41:05.363'),
(10024, 29, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-13 20:45:56.327', N'2026-05-13 20:45:56.327'),
(10025, 10002, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_insight"}', N'2026-05-16 09:27:26.490', N'2026-05-16 09:27:26.490'),
(10026, 10007, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-05-16 09:28:13.217', N'2026-05-16 09:28:13.217'),
(10027, 10006, 3, N'status_change', N'{"from":"deal_masuk","to":"menunggu_draft_ok"}', N'2026-05-16 09:28:38.377', N'2026-05-16 09:28:38.377'),
(10028, 10008, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-05-16 09:31:46.530', N'2026-05-16 09:31:46.530'),
(10029, 10007, 3, N'status_change', N'{"from":"pembelian_produk","to":"pembuatan_draft"}', N'2026-05-16 09:32:04.133', N'2026-05-16 09:32:04.133'),
(10030, 10009, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-05-16 09:32:51.060', N'2026-05-16 09:32:51.060'),
(10031, 42, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"selesai"}', N'2026-05-16 09:33:22.527', N'2026-05-16 09:33:22.527'),
(10032, 44, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-16 09:33:26.407', N'2026-05-16 09:33:26.407'),
(10033, 50, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-16 09:33:32.937', N'2026-05-16 09:33:32.937'),
(10034, 10010, 3, N'create', N'{"status":"menunggu_insight"}', N'2026-05-16 09:35:34.067', N'2026-05-16 09:35:34.067'),
(10035, 10011, 3, N'create', N'{"status":"menunggu_draft_ok"}', N'2026-05-16 09:36:42.857', N'2026-05-16 09:36:42.857'),
(10036, 10012, 3, N'create', N'{"status":"pembuatan_draft"}', N'2026-05-16 09:43:39.090', N'2026-05-16 09:43:39.090'),
(10037, 10005, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-16 09:45:58.377', N'2026-05-16 09:45:58.377'),
(10038, 46, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-16 09:48:25.073', N'2026-05-16 09:48:25.073'),
(10039, 10013, 3, N'create', N'{"status":"menunggu_payment"}', N'2026-05-16 10:01:02.123', N'2026-05-16 10:01:02.123'),
(10040, 39, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-17 05:30:00.510', N'2026-05-17 05:30:00.510'),
(10041, 10012, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-17 16:27:50.747', N'2026-05-17 16:27:50.747'),
(10042, 10008, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-17 16:28:06.613', N'2026-05-17 16:28:06.613'),
(10043, 27, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-18 12:33:09.157', N'2026-05-18 12:33:09.157'),
(10044, 10014, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-05-19 04:15:13.300', N'2026-05-19 04:15:13.300'),
(10045, 10015, 3, N'create', N'{"status":"pembelian_produk"}', N'2026-05-19 04:19:25.183', N'2026-05-19 04:19:25.183'),
(10046, 10015, 3, N'update', N'{"status":"pembelian_produk","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"0.00","to":"325000.00"}}}', N'2026-05-19 04:21:01.410', N'2026-05-19 04:21:01.410'),
(10047, 10014, 3, N'update', N'{"status":"pembelian_produk","fields_changed":["fee_amount"],"changes":{"fee_amount":{"from":"0.00","to":"100000.00"}}}', N'2026-05-19 04:21:36.127', N'2026-05-19 04:21:36.127'),
(10048, 10007, 3, N'status_change', N'{"from":"pembuatan_draft","to":"pembelian_produk"}', N'2026-05-19 04:29:11.063', N'2026-05-19 04:29:11.063'),
(10049, 10009, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_insight"}', N'2026-05-19 04:29:21.913', N'2026-05-19 04:29:21.913'),
(10050, 7, 3, N'status_change', N'{"from":"menunggu_payment","to":"selesai"}', N'2026-05-24 00:41:59.467', N'2026-05-24 00:41:59.467'),
(10051, 41, 3, N'status_change', N'{"from":"pembuatan_draft","to":"menunggu_draft_ok"}', N'2026-05-24 00:44:31.017', N'2026-05-24 00:44:31.017'),
(10052, 10014, 3, N'status_change', N'{"from":"pembelian_produk","to":"menunggu_draft_ok"}', N'2026-05-24 00:45:23.510', N'2026-05-24 00:45:23.510'),
(10053, 10015, 3, N'status_change', N'{"from":"pembelian_produk","to":"menunggu_draft_ok"}', N'2026-05-24 00:45:28.820', N'2026-05-24 00:45:28.820'),
(10054, 10012, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-24 00:46:21.867', N'2026-05-24 00:46:21.867'),
(10055, 10011, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-24 00:46:27.950', N'2026-05-24 00:46:27.950'),
(10056, 10008, 3, N'status_change', N'{"from":"menunggu_draft_ok","to":"menunggu_insight"}', N'2026-05-24 00:47:39.857', N'2026-05-24 00:47:39.857'),
(10057, 10002, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-24 00:59:45.000', N'2026-05-24 00:59:45.000'),
(10058, 10004, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-24 01:00:00.047', N'2026-05-24 01:00:00.047'),
(10059, 48, 3, N'status_change', N'{"from":"menunggu_insight","to":"menunggu_payment"}', N'2026-05-24 01:00:12.123', N'2026-05-24 01:00:12.123');
SET IDENTITY_INSERT [dbo].[endorsement_activities] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[endorsement_revisions]
IF OBJECT_ID(N'dbo.endorsement_revisions', N'U') IS NOT NULL DROP TABLE [dbo].[endorsement_revisions];
CREATE TABLE [dbo].[endorsement_revisions] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [endorsement_id] bigint NOT NULL,
    [revision_date] date NOT NULL,
    [note] nvarchar(max) NULL,
    [uploaded_to_drive] bit DEFAULT ('0') NOT NULL,
    [is_approved] bit DEFAULT ('0') NOT NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    [user_id] bigint NULL,
    CONSTRAINT [PK__endorsem__3213E83F41F10A19] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[endorsement_revisions] ON;
SET IDENTITY_INSERT [dbo].[endorsement_revisions] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[endorsements]
IF OBJECT_ID(N'dbo.endorsements', N'U') IS NOT NULL DROP TABLE [dbo].[endorsements];
CREATE TABLE [dbo].[endorsements] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [brand_name] nvarchar(255) NOT NULL,
    [campaign_name] nvarchar(255) NULL,
    [platform] nvarchar(30) NOT NULL,
    [content_type] nvarchar(30) NOT NULL,
    [status] nvarchar(40) DEFAULT ('deal_masuk') NOT NULL,
    [deal_date] date NULL,
    [product_ordered_at] date NULL,
    [product_received_at] date NULL,
    [draft_deadline] date NULL,
    [storyline_required] bit DEFAULT ('0') NOT NULL,
    [storyline_done] bit DEFAULT ('0') NOT NULL,
    [drive_uploaded] bit DEFAULT ('0') NOT NULL,
    [approved_at] date NULL,
    [posting_date] date NULL,
    [posted_at] date NULL,
    [insight_due_at] date NULL,
    [insight_sent_at] date NULL,
    [boostcode_required] bit DEFAULT ('0') NOT NULL,
    [boostcode_duration_days] smallint NULL,
    [self_purchase] bit DEFAULT ('0') NOT NULL,
    [checkout_proof_path] nvarchar(255) NULL,
    [financial_mode] nvarchar(40) DEFAULT ('reimburse_duluan') NOT NULL,
    [fee_amount] decimal(15,2) DEFAULT ('0') NOT NULL,
    [reimburse_amount] decimal(15,2) DEFAULT ('0') NOT NULL,
    [product_cost] decimal(15,2) DEFAULT ('0') NOT NULL,
    [other_cost] decimal(15,2) DEFAULT ('0') NOT NULL,
    [payment_status] nvarchar(20) DEFAULT ('belum_bayar') NOT NULL,
    [payment_due_date] date NULL,
    [payment_received_date] date NULL,
    [notes] nvarchar(max) NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    [user_id] bigint NULL,
    [deleted_reason] nvarchar(max) NULL,
    [deleted_by] bigint NULL,
    [deleted_at] datetime NULL,
    CONSTRAINT [PK__endorsem__3213E83F8EB6D14C] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[endorsements] ON;
INSERT INTO [dbo].[endorsements] ([id], [brand_name], [campaign_name], [platform], [content_type], [status], [deal_date], [product_ordered_at], [product_received_at], [draft_deadline], [storyline_required], [storyline_done], [drive_uploaded], [approved_at], [posting_date], [posted_at], [insight_due_at], [insight_sent_at], [boostcode_required], [boostcode_duration_days], [self_purchase], [checkout_proof_path], [financial_mode], [fee_amount], [reimburse_amount], [product_cost], [other_cost], [payment_status], [payment_due_date], [payment_received_date], [notes], [created_at], [updated_at], [user_id], [deleted_reason], [deleted_by], [deleted_at]) VALUES
(5, N'Nasgul', N'nasgul baba', N'tiktok', N'video', N'selesai', N'2026-02-20', N'2026-02-23', N'2026-02-23', N'2026-03-02', 0, 0, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 50000.00, .00, 10000.00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-01 08:06:57.647', N'2026-04-26 11:53:16.287', 3, NULL, NULL, NULL),
(6, N'Clogen', N'Penghilang bau kulkas', N'tiktok', N'video', N'selesai', N'2026-02-28', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'reimburse_bersama_fee', 180000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-02 02:55:18.557', N'2026-04-26 13:22:21.900', 3, NULL, NULL, NULL),
(7, N'Sunlife Syariah', N'Asuransi', N'tiktok', N'video', N'selesai', N'2026-02-25', NULL, NULL, NULL, 1, 0, 0, NULL, N'2026-03-10', NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 100000.00, .00, .00, .00, N'lunas', NULL, N'2026-05-24', NULL, N'2026-03-02 02:58:06.343', N'2026-05-24 00:41:59.440', 3, NULL, NULL, NULL),
(8, N'Baby Happy', N'Popok', N'tiktok', N'video', N'selesai', N'2026-02-19', N'2026-02-20', N'2026-02-21', NULL, 0, 0, 1, N'2026-02-23', N'2026-02-24', N'2026-02-24', N'2026-03-03', NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 100000.00, .00, 43000.00, .00, N'lunas', NULL, N'2026-04-28', NULL, N'2026-03-02 03:04:49.947', N'2026-04-28 08:26:26.347', 3, NULL, NULL, NULL),
(9, N'Gatsby', N'pomade', N'tiktok', N'video', N'selesai', N'2026-02-22', N'2026-02-22', N'2026-02-22', NULL, 0, 0, 1, N'2026-02-26', N'2026-02-26', N'2026-02-26', N'2026-03-05', NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 275000.00, .00, 30000.00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-02 03:34:16.263', N'2026-04-26 12:43:24.763', 3, NULL, NULL, NULL),
(10, N'Milna', N'Abon sapi', N'tiktok', N'video', N'selesai', N'2026-02-20', N'2026-02-22', N'2026-02-22', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_duluan', 30000.00, 30000.00, 30000.00, .00, N'lunas', NULL, N'2026-04-28', NULL, N'2026-03-02 03:58:14.393', N'2026-04-28 15:14:49.357', 3, NULL, NULL, NULL),
(11, N'Miyako', N'Kipas angin', N'tiktok', N'video', N'selesai', N'2026-02-20', N'2026-02-21', N'2026-02-21', N'2026-02-21', 0, 0, 1, N'2026-02-26', N'2026-02-26', N'2026-02-26', N'2026-03-05', NULL, 1, 365, 0, NULL, N'na_dikirim_brand', 90000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-28', NULL, N'2026-03-02 04:02:31.520', N'2026-04-28 15:14:38.827', 3, NULL, NULL, NULL),
(12, N'Nasgul', N'Nasgul buna', N'tiktok', N'video', N'selesai', N'2026-02-20', N'2026-02-23', N'2026-02-23', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 50000.00, .00, 10000.00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-02 04:13:32.873', N'2026-04-26 11:53:12.460', 3, NULL, NULL, NULL),
(13, N'Milklife', N'Suhu UHT', N'tiktok', N'video', N'selesai', N'2026-03-02', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_duluan', 15000.00, 143200.00, 143200.00, .00, N'lunas', NULL, N'2026-05-03', NULL, N'2026-03-03 02:55:22.290', N'2026-05-03 06:11:11.137', 3, NULL, NULL, NULL),
(14, N'Waterpark', N'Tropikana', N'tiktok_instagram', N'video', N'selesai', N'2026-03-02', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-03 03:01:36.300', N'2026-04-26 11:53:14.603', 3, NULL, NULL, NULL),
(15, N'Cerebrofrot', N'Edukasi', N'owning_content', N'video', N'pembuatan_draft', NULL, NULL, NULL, NULL, 1, 1, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 490000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-03 03:05:16.747', N'2026-03-29 14:10:21.763', 3, NULL, NULL, NULL),
(16, N'Mundo Baba', N'Kaos kaki baba', N'tiktok', N'video', N'selesai', N'2026-01-13', NULL, N'2026-02-27', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 29000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-03 03:08:08.353', N'2026-04-26 12:42:42.397', 3, NULL, NULL, NULL),
(17, N'Top Coffee', N'Kopi kolak', N'instagram', N'video', N'selesai', N'2026-05-05', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 115000.00, .00, 25000.00, .00, N'lunas', NULL, N'2026-05-03', N'woi bunahh lambat', N'2026-03-05 04:55:14.997', N'2026-05-03 06:11:40.593', 3, NULL, NULL, NULL),
(18, N'Mundo Buna', N'Kaos kaki baba', N'tiktok', N'video', N'selesai', N'2026-01-13', NULL, N'2026-02-27', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 22000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-05 06:36:52.327', N'2026-04-26 12:42:25.983', 3, NULL, NULL, NULL),
(19, N'Royale', N'Royale Sachet 1000', N'tiktok_instagram', N'video', N'menunggu_payment', N'2026-03-06', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 130000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-06 01:32:33.563', N'2026-04-07 04:56:43.013', 3, NULL, NULL, NULL),
(20, N'Terabox', N'Aplikasi AI', N'tiktok', N'video', N'menunggu_payment', N'2026-03-06', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 85000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-06 07:09:43.077', N'2026-04-26 11:18:12.723', 3, NULL, NULL, NULL),
(21, N'firefly', N'sound tiktok', N'tiktok', N'video', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 30000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-07 17:22:09.423', N'2026-04-26 12:54:34.223', 3, NULL, NULL, NULL),
(22, N'Bango', N'Masak Telor Kecap', N'tiktok_instagram', N'video', N'selesai', N'2026-03-11', N'2026-03-11', N'2026-03-11', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 125000.00, .00, 60000.00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-03-11 07:19:50.333', N'2026-04-26 13:21:22.747', 3, NULL, NULL, NULL),
(23, N'GAGA', N'Sarden', N'tiktok_instagram', N'video', N'menunggu_payment', N'2026-03-07', N'2026-03-08', N'2026-03-08', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 40000.00, .00, 25000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-11 07:22:08.067', N'2026-04-26 11:19:24.050', 3, NULL, NULL, NULL),
(24, N'Nutrisari', N'minuman', N'tiktok', N'video', N'menunggu_payment', N'2026-03-25', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 80000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-25 16:05:53.350', N'2026-04-28 16:23:03.037', 3, NULL, NULL, NULL),
(25, N'Nutrisari baba', N'Minuman', N'tiktok', N'video', N'menunggu_payment', N'2026-03-25', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 80000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-25 16:06:47.170', N'2026-04-28 16:23:09.267', 3, NULL, NULL, NULL),
(26, N'Toppoki mamasuka', N'Makanan', N'instagram', N'feed', N'menunggu_payment', N'2026-03-26', N'2026-03-26', N'2026-03-26', N'2026-03-26', 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 30000.00, .00, 15000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-03-26 09:20:10.727', N'2026-04-26 11:19:03.683', 3, NULL, NULL, NULL),
(27, N'Mystery Box', N'Aplikasi', N'instagram', N'reels', N'selesai', N'2026-12-03', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 100000.00, .00, .00, .00, N'lunas', NULL, N'2026-05-18', NULL, N'2026-03-29 13:46:47.607', N'2026-05-18 12:33:09.143', 3, NULL, NULL, NULL),
(28, N'BABY HAPPY', N'diapers', N'tiktok_instagram', N'video', N'selesai', N'2026-04-02', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 180000.00, .00, .00, .00, N'lunas', NULL, N'2026-04-26', NULL, N'2026-04-02 14:50:57.843', N'2026-04-26 13:31:40.287', 3, NULL, NULL, NULL),
(29, N'SUSHI YAY', N'WAGYU', N'instagram', N'reels', N'selesai', N'2026-02-04', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 105000.00, .00, .00, .00, N'lunas', NULL, N'2026-05-13', NULL, N'2026-04-02 14:53:48.990', N'2026-05-13 20:45:56.297', 3, NULL, NULL, NULL),
(30, N'PURA', N'LKALDU', N'tiktok', N'video', N'selesai', N'2026-02-04', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 40000.00, .00, .00, .00, N'lunas', NULL, N'2026-05-09', NULL, N'2026-04-02 15:03:35.570', N'2026-05-09 05:55:07.217', 3, NULL, NULL, NULL),
(31, N'HARPIC', N'PEMBERSIH KLOSET', N'tiktok', N'video', N'menunggu_payment', N'2026-02-04', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 30000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-02 15:05:34.543', N'2026-05-09 04:53:07.797', 3, NULL, NULL, NULL),
(32, N'PARFUM', N'GOOD', N'tiktok', N'video', N'selesai', N'2026-02-04', NULL, N'2026-01-04', NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'lunas', NULL, N'2026-05-04', NULL, N'2026-04-02 15:07:13.440', N'2026-05-04 06:29:39.943', 3, NULL, NULL, NULL),
(33, N'gently', N'sunscreen dan moist', N'tiktok', N'video', N'pembuatan_draft', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-02 15:08:04.507', N'2026-04-02 15:08:04.507', 3, NULL, NULL, NULL),
(34, N'SOYA SIAPAMAU MG', N'SUFOR', N'tiktok', N'video', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 193300.00, .00, 43300.00, .00, N'lunas', NULL, N'2026-05-08', NULL, N'2026-04-02 15:13:22.350', N'2026-05-09 04:17:10.933', 3, NULL, NULL, NULL),
(35, N'Caffino', N'kopi botol', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_duluan', 15000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-05 11:08:59.263', N'2026-05-04 06:29:57.130', 3, NULL, NULL, NULL),
(36, N'Nivea Men', N'Facial Wash', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 65000.00, .00, 30000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-05 11:13:09.443', N'2026-04-26 11:37:28.763', 3, NULL, NULL, NULL),
(37, N'CHILKID SIAPAMAU MG', N'SUFOR', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 135000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-07 05:03:25.073', N'2026-05-09 04:12:47.867', 3, NULL, NULL, NULL),
(38, N'PHP SURYA', N'SUFOR', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 150000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-07 05:07:13.137', N'2026-05-09 04:16:23.440', 3, NULL, NULL, NULL),
(39, N'Gopay', N'3 video', N'instagram', N'video', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 125000.00, .00, .00, .00, N'lunas', NULL, N'2026-05-17', NULL, N'2026-04-09 06:23:53.470', N'2026-05-17 05:30:00.493', 3, NULL, NULL, NULL),
(40, N'YUP', N'RICHEESE', N'tiktok_instagram', N'video', N'menunggu_payment', N'2026-06-04', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_duluan', 320000.00, 25000.00, 25000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-14 08:23:20.320', N'2026-04-26 13:18:25.063', 3, NULL, NULL, NULL),
(41, N'SOZO Klinik', N'Treatment', N'instagram', N'reels', N'menunggu_draft_ok', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 315000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-26 11:27:48.487', N'2026-05-24 00:44:30.987', 3, NULL, NULL, NULL),
(42, N'DOKTER MOBIL', N'2 unit bisnis', N'instagram', N'reels', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'lunas', NULL, N'2026-05-16', NULL, N'2026-04-26 11:28:45.343', N'2026-05-16 09:33:22.500', 3, NULL, NULL, NULL),
(43, N'EVERSHINE', N'spray nyamuk', N'instagram', N'reels', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'lunas', NULL, N'2026-05-08', NULL, N'2026-04-26 13:01:23.610', N'2026-05-08 17:42:28.840', 3, NULL, NULL, NULL),
(44, N'OB HERBAL', N'obat batuk', N'tiktok', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_duluan', 75000.00, 30000.00, 30000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-26 13:04:20.127', N'2026-05-16 09:33:26.397', 3, NULL, NULL, NULL),
(45, N'SUNREI', N'lampu', N'instagram', N'reels', N'pembuatan_draft', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-26 13:07:56.050', N'2026-04-26 13:07:56.050', 3, NULL, NULL, NULL),
(46, N'PHP MALIKA', N'SUFOR', N'instagram', N'reels', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 300000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-26 13:15:39.347', N'2026-05-16 09:48:25.060', 3, NULL, NULL, NULL),
(47, N'CHILKID 1,5KG', N'SUFOR', N'instagram', N'reels', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 150000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-26 13:17:21.107', N'2026-05-09 04:14:01.697', 3, NULL, NULL, NULL),
(48, N'CHIL*GO', N'Chilgo', N'tiktok_instagram', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 150000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-28 09:55:13.127', N'2026-05-24 01:00:12.110', 3, NULL, NULL, NULL),
(49, N'CITRA RAYA', N'WATERWORLD', N'instagram', N'reels', N'selesai', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'lunas', NULL, N'2026-04-28', NULL, N'2026-04-28 09:55:59.883', N'2026-04-28 09:55:59.883', 3, NULL, NULL, NULL),
(50, N'SIANTAR TOP', N'Party Pack', N'tiktok', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', .00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-04-28 16:33:57.233', N'2026-05-16 09:33:32.923', 3, NULL, NULL, NULL),
(10002, N'CHILKID UNGGUL DIGITAL', N'SUFOR', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 300000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-09 04:33:38.327', N'2026-05-24 00:59:44.983', 3, NULL, NULL, NULL),
(10003, N'CHILKID SURYA', N'SUFOR', N'tiktok', N'video', N'menunggu_draft_ok', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 200000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-09 04:34:01.907', N'2026-05-09 04:38:01.267', 3, NULL, NULL, NULL),
(10004, N'SWIMWEAR', N'ALIVIA HOUSE', N'tiktok', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 50000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-09 04:40:02.217', N'2026-05-24 01:00:00.003', 3, NULL, NULL, NULL),
(10005, N'yup rtp', N'3 akun', N'tiktok_instagram', N'video', N'menunggu_payment', N'2026-05-04', NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 390000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-10 14:35:43.920', N'2026-05-16 09:45:58.360', 3, NULL, NULL, NULL),
(10006, N'rtp thean', N'yup', N'tiktok', N'video', N'menunggu_draft_ok', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 70000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-10 14:41:05.337', N'2026-05-16 09:28:38.367', 3, NULL, NULL, NULL),
(10007, N'MORINAGA PIC IQBAL', N'CHILKID', N'instagram', N'reels', N'pembelian_produk', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 350000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:28:13.173', N'2026-05-19 04:29:11.047', 3, NULL, NULL, NULL),
(10008, N'PHP ODYSSEY', NULL, N'tiktok', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 125000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:31:46.397', N'2026-05-24 00:47:39.847', 3, NULL, NULL, NULL),
(10009, N'SPARKSSPORTS', N'REVIEW', N'tiktok_instagram', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 300000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:32:51.043', N'2026-05-19 04:29:21.903', 3, NULL, NULL, NULL),
(10010, N'YUMMY COIN', N'VISIT GIANY', N'tiktok_instagram', N'feed', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 120000.00, .00, 25000.00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:35:34.037', N'2026-05-16 09:35:34.037', 3, NULL, NULL, NULL),
(10011, N'SAMSUNG', N'TWS', N'tiktok', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 190000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:36:42.840', N'2026-05-24 00:46:27.937', 3, NULL, NULL, NULL),
(10012, N'SLEEK 2VT', N'RATING', N'tiktok', N'video', N'menunggu_insight', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, N'reimburse_bersama_fee', 200000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 09:43:39.047', N'2026-05-24 00:46:21.857', 3, NULL, NULL, NULL),
(10013, N'REDBUS', N'CAMPAIGN', N'tiktok_instagram', N'video', N'menunggu_payment', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_tanpa_produk', 200000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-16 10:01:02.077', N'2026-05-16 10:01:02.077', 3, NULL, NULL, NULL),
(10014, N'dobha perfume', N'campaign 3ml', N'tiktok_instagram', N'video', N'menunggu_draft_ok', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 100000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-19 04:15:13.203', N'2026-05-24 00:45:23.497', 3, NULL, NULL, NULL),
(10015, N'PIGEON', N'botol anak', N'instagram', N'video', N'menunggu_draft_ok', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, N'na_dikirim_brand', 325000.00, .00, .00, .00, N'belum_bayar', NULL, NULL, NULL, N'2026-05-19 04:19:25.167', N'2026-05-24 00:45:28.807', 3, NULL, NULL, NULL);
SET IDENTITY_INSERT [dbo].[endorsements] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[failed_jobs]
IF OBJECT_ID(N'dbo.failed_jobs', N'U') IS NOT NULL DROP TABLE [dbo].[failed_jobs];
CREATE TABLE [dbo].[failed_jobs] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [uuid] nvarchar(255) NOT NULL,
    [connection] nvarchar(max) NOT NULL,
    [queue] nvarchar(max) NOT NULL,
    [payload] nvarchar(max) NOT NULL,
    [exception] nvarchar(max) NOT NULL,
    [failed_at] datetime DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK__failed_j__3213E83FCF213B60] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[failed_jobs] ON;
SET IDENTITY_INSERT [dbo].[failed_jobs] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[job_batches]
IF OBJECT_ID(N'dbo.job_batches', N'U') IS NOT NULL DROP TABLE [dbo].[job_batches];
CREATE TABLE [dbo].[job_batches] (
    [id] nvarchar(255) NOT NULL,
    [name] nvarchar(255) NOT NULL,
    [total_jobs] int NOT NULL,
    [pending_jobs] int NOT NULL,
    [failed_jobs] int NOT NULL,
    [failed_job_ids] nvarchar(max) NOT NULL,
    [options] nvarchar(max) NULL,
    [cancelled_at] int NULL,
    [created_at] int NOT NULL,
    [finished_at] int NULL,
    CONSTRAINT [job_batches_id_primary] PRIMARY KEY ([id])
);

-- ------------------------------------------------------------------
-- Table: [dbo].[jobs]
IF OBJECT_ID(N'dbo.jobs', N'U') IS NOT NULL DROP TABLE [dbo].[jobs];
CREATE TABLE [dbo].[jobs] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [queue] nvarchar(255) NOT NULL,
    [payload] nvarchar(max) NOT NULL,
    [attempts] tinyint NOT NULL,
    [reserved_at] int NULL,
    [available_at] int NOT NULL,
    [created_at] int NOT NULL,
    CONSTRAINT [PK__jobs__3213E83F1465F13E] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[jobs] ON;
SET IDENTITY_INSERT [dbo].[jobs] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[migrations]
IF OBJECT_ID(N'dbo.migrations', N'U') IS NOT NULL DROP TABLE [dbo].[migrations];
CREATE TABLE [dbo].[migrations] (
    [id] int IDENTITY(1,1) NOT NULL,
    [migration] nvarchar(255) NOT NULL,
    [batch] int NOT NULL,
    CONSTRAINT [PK__migratio__3213E83FA19FA608] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[migrations] ON;
INSERT INTO [dbo].[migrations] ([id], [migration], [batch]) VALUES
(1, N'0001_01_01_000000_create_users_table', 1),
(2, N'0001_01_01_000001_create_cache_table', 1),
(3, N'0001_01_01_000002_create_jobs_table', 1),
(4, N'2026_03_01_070120_create_endorsements_table', 1),
(5, N'2026_03_01_070121_create_endorsement_revisions_table', 1),
(6, N'2026_03_03_074007_replace_sudah_posting_with_menunggu_insight_on_endorsements_table', 1),
(7, N'2026_03_07_000001_create_endorsement_activities_table', 1),
(8, N'2026_03_07_054220_drop_telescope_tables', 1),
(9, N'2026_03_07_060759_add_account_fields_to_users_table', 1),
(10, N'2026_03_07_060829_add_user_id_to_endorsements_and_revisions', 1),
(11, N'2026_03_17_000000_add_soft_deletes_and_reason_to_endorsements_table', 1),
(12, N'2026_03_18_000000_create_user_login_activities_table', 1),
(13, N'2026_03_18_010000_add_session_code_to_users_table', 1),
(14, N'2026_03_27_000001_drop_endorsement_files_table', 1),
(15, N'2026_04_26_000001_create_pemasukan_table', 1),
(16, N'2026_04_26_000002_create_pengeluaran_table', 1),
(1002, N'2026_05_09_090000_create_backup_settings_table', 2),
(1003, N'2026_05_09_090100_create_backup_logs_table', 2);
SET IDENTITY_INSERT [dbo].[migrations] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[password_reset_tokens]
IF OBJECT_ID(N'dbo.password_reset_tokens', N'U') IS NOT NULL DROP TABLE [dbo].[password_reset_tokens];
CREATE TABLE [dbo].[password_reset_tokens] (
    [email] nvarchar(255) NOT NULL,
    [token] nvarchar(255) NOT NULL,
    [created_at] datetime NULL,
    CONSTRAINT [password_reset_tokens_email_primary] PRIMARY KEY ([email])
);

-- ------------------------------------------------------------------
-- Table: [dbo].[pemasukan]
IF OBJECT_ID(N'dbo.pemasukan', N'U') IS NOT NULL DROP TABLE [dbo].[pemasukan];
CREATE TABLE [dbo].[pemasukan] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [user_id] bigint NOT NULL,
    [tanggal] date NOT NULL,
    [deskripsi] nvarchar(255) NOT NULL,
    [jumlah] decimal(15,2) DEFAULT ('0') NOT NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__pemasuka__3213E83FEBFD818E] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[pemasukan] ON;
INSERT INTO [dbo].[pemasukan] ([id], [user_id], [tanggal], [deskripsi], [jumlah], [created_at], [updated_at]) VALUES
(2, 3, N'2026-04-26', N'Saldo Awal', 298600.00, N'2026-04-26 12:40:30.217', N'2026-04-30 05:23:20.557'),
(3, 3, N'2026-05-06', N'sparksports', 565000.00, N'2026-05-05 20:57:03.623', N'2026-05-05 20:57:03.623'),
(10002, 3, N'2026-05-10', N'saldo digital MORINAGA', 20000.00, N'2026-05-10 14:37:22.183', N'2026-05-10 14:37:22.183'),
(10003, 3, N'2026-05-13', N'saldo digital MORINAGA', 30000.00, N'2026-05-13 20:50:28.107', N'2026-05-13 20:50:28.107'),
(10004, 3, N'2026-05-19', N'capcut pro', 29500.00, N'2026-05-19 11:53:01.910', N'2026-05-19 11:56:38.570');
SET IDENTITY_INSERT [dbo].[pemasukan] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[pengeluaran]
IF OBJECT_ID(N'dbo.pengeluaran', N'U') IS NOT NULL DROP TABLE [dbo].[pengeluaran];
CREATE TABLE [dbo].[pengeluaran] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [user_id] bigint NOT NULL,
    [tanggal] date NOT NULL,
    [deskripsi] nvarchar(255) NOT NULL,
    [jumlah] decimal(15,2) DEFAULT ('0') NOT NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__pengelua__3213E83F11D6217A] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[pengeluaran] ON;
INSERT INTO [dbo].[pengeluaran] ([id], [user_id], [tanggal], [deskripsi], [jumlah], [created_at], [updated_at]) VALUES
(2, 3, N'2026-04-28', N'MORINAGA PHP', 177000.00, N'2026-04-28 08:19:01.430', N'2026-04-28 08:19:01.430'),
(3, 3, N'2026-04-28', N'gift baba', 150000.00, N'2026-04-28 08:24:31.257', N'2026-04-28 08:24:31.257'),
(5, 3, N'2026-04-28', N'parkir', 11000.00, N'2026-04-28 08:25:02.757', N'2026-04-28 08:25:02.757'),
(6, 3, N'2026-04-28', N'gift buna', 268000.00, N'2026-04-28 09:48:44.547', N'2026-04-28 09:48:44.547'),
(7, 3, N'2026-04-28', N'asuransi gopay', 10000.00, N'2026-04-28 16:27:42.827', N'2026-04-28 16:27:42.827'),
(8, 3, N'2026-04-29', N'Support by else', 15000.00, N'2026-04-29 08:53:43.667', N'2026-04-29 08:53:43.667'),
(10, 3, N'2026-04-30', N'morinaga chilgo', 20000.00, N'2026-04-30 05:17:07.083', N'2026-04-30 05:17:07.083'),
(11, 3, N'2026-05-03', N'support else', 45000.00, N'2026-05-03 06:13:45.707', N'2026-05-03 06:13:45.707'),
(12, 3, N'2026-05-01', N'v1pedia', 20000.00, N'2026-05-03 06:14:52.297', N'2026-05-03 06:14:52.297'),
(13, 3, N'2026-05-06', N'servis hp buna', 300000.00, N'2026-05-05 20:57:25.717', N'2026-05-05 20:57:25.717'),
(10002, 3, N'2026-05-06', N'dipinjem mama', 200000.00, N'2026-05-08 17:47:47.543', N'2026-05-08 17:47:47.543'),
(10003, 3, N'2026-05-06', N'support else', 15000.00, N'2026-05-08 17:49:30.673', N'2026-05-08 17:49:30.673'),
(10004, 3, N'2026-05-09', N'dipinjem mama', 300000.00, N'2026-05-09 05:55:34.307', N'2026-05-09 05:55:34.307'),
(10005, 3, N'2026-05-10', N'joki 3 tt RTP YUP', 45000.00, N'2026-05-10 14:36:14.970', N'2026-05-10 14:36:14.970'),
(10006, 3, N'2026-05-10', N'dana kaget', 15000.00, N'2026-05-10 14:38:15.680', N'2026-05-10 14:38:15.680'),
(10007, 3, N'2026-05-13', N'sleek', 13200.00, N'2026-05-13 20:49:42.337', N'2026-05-13 20:49:42.337'),
(10008, 3, N'2026-05-16', N'traktir maratun', 150000.00, N'2026-05-16 09:18:24.273', N'2026-05-16 09:18:24.273'),
(10009, 3, N'2026-05-15', N'joki tt', 45000.00, N'2026-05-16 09:18:43.677', N'2026-05-16 09:18:43.677'),
(10010, 3, N'2026-05-14', N'yummy coin', 25000.00, N'2026-05-16 09:19:30.850', N'2026-05-16 09:19:30.850'),
(10011, 3, N'2026-05-16', N'parkir visit', 11000.00, N'2026-05-16 09:19:49.150', N'2026-05-16 09:19:49.150'),
(10012, 3, N'2026-05-17', N'dipinjem mama', 200000.00, N'2026-05-17 03:23:50.180', N'2026-05-17 03:23:50.180'),
(10013, 3, N'2026-05-19', N'dahlia pengharum 2 pcs', 21000.00, N'2026-05-19 11:52:13.100', N'2026-05-19 11:52:13.100'),
(10014, 3, N'2026-05-19', N'capcut pro', 12000.00, N'2026-05-19 11:52:33.503', N'2026-05-19 11:54:29.407'),
(10015, 3, N'2026-05-19', N'capcut pro', 12000.00, N'2026-05-19 11:52:38.540', N'2026-05-19 11:54:20.667'),
(10016, 3, N'2026-05-24', N'joki 600 like', 20000.00, N'2026-05-24 00:40:49.570', N'2026-05-24 00:40:49.570'),
(10017, 3, N'2026-05-24', N'joki 70 like komen', 15000.00, N'2026-05-24 00:41:11.257', N'2026-05-24 00:41:11.257'),
(10018, 3, N'2026-05-24', N'promosi tt ntar di rembes', 92000.00, N'2026-05-24 00:43:26.947', N'2026-05-24 00:43:26.947');
SET IDENTITY_INSERT [dbo].[pengeluaran] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[sessions]
IF OBJECT_ID(N'dbo.sessions', N'U') IS NOT NULL DROP TABLE [dbo].[sessions];
CREATE TABLE [dbo].[sessions] (
    [id] nvarchar(255) NOT NULL,
    [user_id] bigint NULL,
    [ip_address] nvarchar(45) NULL,
    [user_agent] nvarchar(max) NULL,
    [payload] nvarchar(max) NOT NULL,
    [last_activity] int NOT NULL,
    CONSTRAINT [sessions_id_primary] PRIMARY KEY ([id])
);
INSERT INTO [dbo].[sessions] ([id], [user_id], [ip_address], [user_agent], [payload], [last_activity]) VALUES
(N'0szQHNd4JalC4h07JORjJXxTA12f42dhLQVLwVRj', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiU0NuN1pLTm1GeHp2WnFQbHNQZUMwMDFBbG9MWDZ0NjJWSFRBa1FCNSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290332),
(N'1zQD5PyatEpFeOFfisFReH0UlSiZtspt8nLkrRxq', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiQmJ4MnVFd1ljNDR0bEdhZEpmNjk5SnlBYU9rMFU3UkJ3c1lFbkJNUSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290420),
(N'2nKFrfiIQGYOKFKsieSs7BlD0oYufjuTKtVmh3gU', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiWVZmS1NQOXo3bllOQWxFamZFOGs2R0lVdGtrOVRqTkk3dHBBdGZGSCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290407),
(N'3uDCYvLjgxIx4NYOCOapCusNZl9WlE83jAIBnqx3', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiTlJzc05MeUZVenc2OWRPRVd0djc2MzNxQzlUdzVRSjRPVFVpeVYyNSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290375),
(N'4m0bJTn81ZaJvnO7nR8C1XbQtx6DbTI206MEfLIK', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiM055WE5BdnV2UmRTQnNNYkhsVnZWV0d3MzFMZDNoZTFrODYyeE9yOSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778656281),
(N'4tfEywo1Q7e6FQzAa5qVcad4Pfha4Ef0n3nSZr1s', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiTTdtWkNIeXo4UzFTc1R1dlNvTjB2NklzeEdBWm1RckI5N1dySDRsViI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290412),
(N'63pHdW9Bh3pPUGWARzm4MA5pbv6T610t9ykevVjw', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoid2lRRW5zYnZueDk0T2NZYmNzUG53N1Q2OUZNUlBtZU54Z3VGUlViNyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290410),
(N'6cxAXDWv5DfaCrqzg05o60Jwk9Ue9eSxmJg3IPfs', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiMEpvZWI5RmpxMXV5U1NDS1VpcUVJc0YzbXRCUmtvSmtsTDdtQTk2ZyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290332),
(N'7CE53v0FJteiTnyvb4WSABD1lMHMwtaUkeC0kSjN', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiZ2JDY2RkT2pBdTZyeUJucHQ4Y3pIdldBMjFHUUZQUFFIZGtDeVRzdCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290325),
(N'8any5Aupw0hfqSdwxN9hRo9aw23TPcCrMZpEksXT', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiSlRXOEZTRVlpVzhxajNKa2RxeGltbjVjTkdVUlNGdVEzZHFVNnFZRyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290423),
(N'9JkC07VJ8zG6YTZROEyMVwfeHZP4O7KUgxxEmy7e', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiS1c3dzFqU3QybWdxMkJOUENqTTZ6V3dOUVU5djloS0FRNWZpRlMwVyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290404),
(N'9n0oVL7D66Pf8pmAbIeoIxtI1EuBn1CvUnv0LSlX', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiN1NiaGppZFR2a0VJam4xeDAwVjVvVDRrWW85YkVxRVVnU0FhcTJIOCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290422),
(N'9x0mkmIpSTtYVpW59w2cr3sstyTuxZkTrJJAtc8W', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiWEFXQTQ5TUNEWUF0MGxXMDNCdXBCOVFxaThhNHgzd1lMRG5PejlTRSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290417),
(N'aijyGA7azq3qeYSHiPDBOAFaZjexwnoy82TGgkUu', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiangzcW52TnBGR2l0aU5HSUo3UUx1d2tLcERzZ1NYSEZtNUl3UHlUSSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290328),
(N'AoP67wF5PqUXHIZUQgDW9wtEXNNxItSjCW8mM9XB', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiWVRIQXhKNk9XdVFyS3oxZFdPZ3FqNDhmd21VdXJYdWtvRDVoVXlVTiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290405),
(N'B62NZjtcJ9hv324j98jCPpG7hKVG2JnhfpEk37d8', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiaFpjanRaT2F0V2JxVVdrdUZXRVdUbjZXOU13NDBERjNEYXZWY3lwOSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290375),
(N'bihCpbWinAS3Z3c62IKmLDJjO6Ej7B3Xz5OQL6d2', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiMmcxSHZ2NEFpMUNPUEZoODRheWt2cXBkUkhCZlp6Q0ZVdlV6aDJ5bCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290404),
(N'coozfWLbIevcSwZKj5i2x7XWiekQwluH9Ep3aftP', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiTXJXam1haW1QQ2o3RjQ2YzUyYXc5d2JPUndBVUw3ZFZyQklvUjg3YiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290327),
(N'CYgWBlckv5Je02hyMsdULTtCsnnti6QZdOLHBkad', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiZjF2VUdjWVpTTmtiTGJ2elhaeWgzRWhsa2pEQ2psUFo4aUVoMXZPQiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290377),
(N'dAvcydKrAWFtw2S1eDYtkbJmhEwqOSQiJlGBsKlH', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiZWtYSGlTVGJMYUxhUUlyVzFoOGhMcG01MmN3RVh4NWtUb0NGRmlaaSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290333),
(N'Dnfjc6SxFMDXhTbcF5CUrjNqnUzcCmTdsD5XLpgc', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiejNVd1JKdERWcHYxc1NIaFhCdlhTdERmaFM1WTZQcEpERTh1eUdnVyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290373),
(N'Dp8gs9WpUguJAVqgLQ8w1DuCHC7EeQGxF11p7Vyl', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiOVdiNnBPYXpqck1VMmk5aTk1NEFDck5BRmlYcGJBN1h3YWxQbDFlNyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290334),
(N'eERVXDZytbySGyOKce3UBwdfgReAd3vRrQcY9qVh', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoicWludktNT0F3OTJiemVsVGlEdzh1dUNjSUg0Z2xCUkZZQUlvYk01MiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290329),
(N'EIULKwjMowH1aK0N8CCv4tMfllR1S7kes3H4Ipk5', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiRU5rSTJXeVRzZXVpZjgzT1NSc2JmdnZrTllTQjcwcEJxdnhyUlVYOCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290379),
(N'elay8VfCDCoJeeRjnw31UBG9KSNJdmWFVunrJOzM', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiMjVJN1ZLdnBWa1hnNXkyMk15ejVnaEpRRkhjc2VYQXppNGhmWjN4NSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290378),
(N'eql3VIu66aKTo6F0QYXZpzX3ZLql0TFdjhjmFNu2', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiRnRsWjFJZ2pOazFtTkJseXlQemhlTnVRekZKV1FVOElPbE5SUkU3VSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mzg6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC8/X2xhcmF2ZWxfYnJhaW49IjtzOjU6InJvdXRlIjtzOjc6ImxhbmRpbmciO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX19', 1778290273),
(N'EvuPFWvDBBOpehTMMCWentvyX7luPrfTHP70L21n', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVElhNnY2N3NCZTU4S1RobVRZd3h2TURFZ2RjWURhc1ludUN6SldHbyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290408),
(N'g5QeRpx3SxSBTCna7r3F5JA14CCIRUANcziWffZY', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiNzFhOHU3U2VIYVVaenJ3d0VaT3lQMXlxbFN1eU1iWmRnY0Y4QnN5QyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290326),
(N'Gc8GRaCOltnMS0gcSDSKXETfHNgJgFX1h2groxi5', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiaURkSXFxT1FVdGFiN2MwcGhHZWFXUUliMDU2dEF6NGJ2a3ZwQ1B0NyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mzg6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC8/X2xhcmF2ZWwtYnJhaW49IjtzOjU6InJvdXRlIjtzOjc6ImxhbmRpbmciO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX19', 1778290279),
(N'Gf2FhQLcBe0meXI1olXlj6aQP5NwVjxhVpSn2zLn', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YToyOntzOjY6Il90b2tlbiI7czo0MDoiUndIY2gzbVpLOTAyZzRPRVh4RGxYUDU0Y3JjbXFRSm1ZYmdrWHhqZCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778656289),
(N'gKlnJ0iv6RDP0wAqVMzAz5sfSFJpMr2tECqeCrmp', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiU1JjRUtBVHI3V0d5djI1N0pBTG9YQUpISXZ5a0RZRFY0R2F0ZEN2SyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7czo3OiJsYW5kaW5nIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778656277),
(N'Gr7Bu6l6G9chAqtpOO3OcuFTU4Jwk3GRRBUpeaEi', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiSXBZOHowazdFakVnQlF3U1lEMzc2OW9RMkl5UGd2SnJrUUtQd0hkTiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290381),
(N'hAyOlYzjAkFuTC8tKUkFHWPWsLEacMP0O5wDryuH', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiWDczbXRvUklOcUNqTzlVNVc2Q1pRUm5SaUpES3QzcDRabWJjV2VkQyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290410),
(N'iedtrpkj1Dy0mrCo0p9EflQ1l4oCnajvsVUVOmSX', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiaVowU0FKeEJBN1BKV1UzQXpBYldSZXFuZ2hOaTZRT3NTTE1XbVdMZiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290331),
(N'iGg0ZngD8njTPwICXrnSG03ml890SmVSKmXgbiJN', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiU3JGU2pIeWwxYTNxc09xRGFhOWtrOTY0RVg3VEVBdzJQU0hRdm43ZSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290379),
(N'J9JTsQmdbCzNJD87F9V5YZvcL9PMiNPAHLu9HAGL', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiOFlFQ3NHSWpnZ3g4bzNWYkZNRnNabTB3c2xHRHlzWDg0NmRoTWE4ciI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290420),
(N'JQumSTaR8DkV8geFb0xWmOH4FN67PQ1BLHmlu7A8', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoieVJPd0REenh2V1pHRWI1ajRnZldPM3Y2dFMyV09sV0g4U0NWVkNvVSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290326),
(N'JVN4BUYFue6a4tH6UXKsngzxYJEHxs8CjZT0gvJi', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVHRFVDdoRFhoS1ZlR29oaEZWZVpRTFI3U2t1dTgxMDJBMEFXNUxYbyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290424),
(N'JwfDkfHgCZ4uu9cjQF7EgA2xqgiVQuWNYzxTD1lM', NULL, N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiN3JxVmgxakIzWG93QmNSMGhOSXlyM3BNaDhNd2Z2WFNIMlBNMUdMcSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7czo3OiJsYW5kaW5nIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290267),
(N'JzXG22xlIc30Huk4Vdios5Bo8iOeo4wTTUoKVeJq', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoieWFlNVZ1eVZzbUJpb2xPUENIMmFZbnhMTkFQYkdqNFFid1ZpUE1jZiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290408),
(N'L9WChoao58jbmp2G88uLpk66xddkViMt51wgZR4a', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoieGx1dm5iMDJnbThOOGtzaW1YQk1KM1FLZ00yejJYN3dpcHM1VjBVSCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290373),
(N'M8RDuwRkCqqwS7bUqnvzFj5wVFDTJ2YnJbdHmDiv', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoielFzYkR0TGhmRVp2Rm9wc0F4Zml2c0tYSXRIaDdlVnYzcDlkRHd6YiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290335),
(N'mdTrLZOPZ7v5TsivIR6FKeJuIqdtiLFdaaR8O3lo', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiY2pyd2MyYXVFSFN0bWRXckpIb2VpUm13QmV2d2hhQjhsUEcyeEtTUCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290406),
(N'mioJV0Gd2OevO7a4zTJiJnrRZlG4S2UyV1tx2yyE', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiN01iMHloaFZnNVBiTDZkazJDak1qem1NODBxY2VMN2dEbGVvaVFBdiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290376),
(N'MPAuAM7oOqjALX9Y2MjWlvr72OOWsWu6V5VNfEJ6', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiU3dmRXRmbFprSnpLcHZDSjE5Qk5IMEZSVmtWenl1dW16M0IzTTkwdyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290409),
(N'mtDWrOmdAaUKKr3m9o44V46lh0sopYiHDbOPpJpR', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiUmx1d2JuYkhOTHV4Y2RTOFZZdml4eFhXWUdCeVZjQ0pXR1p6VU52QyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290418),
(N'mzr59A49v5PutNisoA4y29s0lZG3AhfzIzsjUdi5', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoidHAxaGdlVmVHc25iZzlxcDN6N2hBYjc3QlI5UU5Bb1lUcml2bHdqaCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290411),
(N'NHqXXc80dheCq5XvgbbYYkgPqwnukHaEPVt9AJCe', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiRzJ6RlV2UnJyM0dESUU5bWVQNE1Mcm1wUVBrMkNHQm9YUEE2ZElsZCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290412),
(N'NHuCvVyUTsZcymXCf4OsITolW4Hyv0JL3eACO54r', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoidE91SGhacVc1WGZNSjB5eFBqWUNSanRkbkhWS1NNalRieDZZYjYyeCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290335),
(N'NtEo2Ws4Jk7RCu6O8inVOc2hNR2FDDWyfL3CXqSg', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiOXUwOVppQ3pVVW5kT3k4cUtPQ042MVNCZDg0djBtZUFDT01hMmJMbSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290406),
(N'nWUbz1lNmnJsdCJtpHMHGIABSKveXUbVzoMTw3P2', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiZUlRMjdJZWdVZ212NWE0dXVDQXlsVHhYMWFSUDd3Q293RGFsVzh6OCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290424),
(N'nxxCsheN9hN8wCpqDCXZ3A0Tcm8QA2ECKnHCwdQP', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiYW1DSmx6TmpvOXA0QmRmeGVjSnZva1RqcWZLVFRvRmJnUU9pM1F0dSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290416),
(N'o8xR0xCKBMkdJfKfDFbX58RmU2o2ouHyDfHjexqr', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiaDJSMXhtd1VrdlowOE9EbjY1T0piSzgyZjhCbW5DMUptVWphUnRlUCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290329),
(N'OI2EollB8JSI6dWst1fmgvMJbzbaQ7ZsJBAA1zIq', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiM094T1FqSGpNTWxsMmgza0FMRkxIUzVHazRnTVNvSW9laXNsMjVKSiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290409),
(N'oKMJkx20CsDzAeBM52owXVooHsQtevXqBNb5p5Fl', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiMkJNR3JtcUFwZWl0M0NkYXdheXQ1djZZemZHOE5zYXpHbXFQc0w1YSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290381),
(N'Oob2gIxThon4Jswmvt4hJsOW7xNDqYhM9JKns7SU', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVldUN0Ywc1dxMnFwWDFEblBCUXgzN0xqRXN5aW1OOG05WG5zempaRyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290327),
(N'OP7Qex31iBuR9A4kSMYM5bJVVQ7duOHeyZQc0icx', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiSGJYZG44ZTQ1WkNsNHQyQnJTVXFyRVF0Q01oTVNmTXdzcjdMS3Y1eSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290420),
(N'OPPFEVOPxYsq1OJqMa6xDy49AKB0ZvRWp2BFLZ0K', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVGFkWmFXb3NjSG5HbjViTlAyR09LRmNTMTlkRW8zYklqWWEwMmZlYyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290330),
(N'oZyuJ6f83U8v0FYJExsybgFN2H8uWl5h5nyeEhLG', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiT2hNNWNoQXVWc1EwejdWZ1Juc1ByVzV5aHUwQnhLOFFwTVRDeERFeiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290372),
(N'PEE6UKOxBY1pZdOoyNck0EnPkWgb3TD5mn3vP9PR', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiaXF2d2g0MDNDSEdnS1ZTU2NuYXQwTzhyTjlhejN2cjFyRUQ1R29GZSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290374),
(N'PldipLtoj6qDdfmxqlMwuGAzNnuMIX6Vjxk3L4qc', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiM3czeWg5UDk0WmEzSmFkQjdMMEdzb2oxcWtpYmtjcG15MzNZZHdnaSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290376),
(N'PmJMe77Ev4MGHq5QTqbuEEqT9q9Ar84SiMMzBCwE', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoicDk0VXJ6aGdPZFV6NGdDM1htVjFhNGxUYXkxaDRtTTY5MHU0ZjdsayI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290416),
(N'RCKAKx5izdZ0p08NuQpu0NDaY4z5nMVr4RqaTEz1', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiT0VmU28wQ2piTFRtdUppcDM0RUZFWGNHZVdwRHlHcmRlMmxtZ054TiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290405),
(N'REi5ZBdwKECeH6Si3Lvxt4zytH3eepB1QbUuqGXX', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVFZKM1czNFJXOEFlMGhFZXkzWktNU25mVGg4cUNsNlMzeDVETmRjWSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290407),
(N'REJUTgYDx6WIyjbyJgGxa17uMKOKqfp6lhIwKRth', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiNmo3QVVQT0ZrWHhZc09SRmFJdTkxeUkyUldkWkpLWE0zNmk3bmVuciI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290375),
(N'rgZaT8zUesB3oPVJys9QCAfWFeZUpc3MUQejZ6X1', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiQVF1WXlaamZDVXd2aUZUVTc0U01iZHBpbHZTYm9SdHZyYjRZeEtOVSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290422),
(N'RqZBDZZKa5w6207IL0i6N4whWFCjBwMYdrmtSEvd', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiRkcxWlVRakd2R1lncGdweHRFUmowcnNHRTA0eDMwdXNkbnU1akYyOCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290381),
(N's3eaR7A3uYMyyWBmrusNNnQ7YJCwwEOYaxlCW6P3', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiNlVSRmtkQ2pWV1VsSFJyVTFOVEVNNlVMUGVJV0NXeExEWjY2MGlxSiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290382),
(N'sNGWMighGyNVJxOVMQXhocAO31bBX2dkkLPior0h', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVXZ2NXlhdFA1Vk9Gb25nQk42Wlp5a2ZNbVJQdDcyUHhuRGJ0RFZMayI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290421),
(N'TDISPmtKuec8SIXxOfxWqkAyTEtGrM7uxAhg3y6f', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiRkxxUjZuVzFEWTBibmFQNm43dHBKWlVIQzZwNkZkbVJsN3BxM0NxUSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290415),
(N'TnXk0HSYQ7VOU2AMGCNIr0tFpEEh7YUKeK9vjIvM', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiZnFQZWt5TTRSdGJkQkcxSXVua2loYzNjS0djMDBTYU9rYkc4d3dDdiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290412),
(N'U3p5Xh0j574x4URDuk4sL3ovOlJRnN0cnyu3MlYA', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiQ2kzQVZvamxNaktqeGNSNEtISG1qVGdWdUdTOGVGY1dlWFdJMUVScyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290325),
(N'UoTkfbFlTo9zzeoTOVkNv686dfseynmLA2enUTa7', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiVUxpeWRjdmRuYzl2ZDYyQUJEaWZUajNITVVSVTJBSWVDOUJUMUpTeiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290419),
(N'uYT3dWcVNrvE1olMlFu7wG1DlFO7E5MmUcjKMM8C', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiOVdFYlROUllkU0J6d0R0ZXhzdVl6c1doQXk1Q0pSVHJ6dW1OZXd3RiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290417),
(N'VgPgvytOfVhJezhwAZPtfmZTxV4zwpaHQmIneenY', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiS0JhNUZvT1NzcUh0Y0w4NmtieUV3WG5yb2NPOHBpdTUzWHFOUnBLdiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMiO3M6NToicm91dGUiO3M6MTg6ImVuZG9yc2VtZW50cy5pbmRleCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290403),
(N'ViwtGTuhuHdYqJmqK8o1g7fO4ui2YElr7mYi3ap5', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiNDl3NTZUZFZWdjBOYnJmTkZOUFdIU0Vua2F6MDh4blhKak44OEFRMCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290423),
(N'vLhI1IWYd3wz1csofvzcZ8xwBbU7ltbkwIKpKlN5', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoidDJiVkR1dEFYMkVZTnZWTDdpc0J3WmZ4ZlNxNms5bjRjZXl4WkFtRSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290331),
(N'vsiX6ZOimcQLK7V5UCP5oPpdgLA7BeS2uoNknbIn', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiNmJ3bnFCVmpzR2hvd1RvZ3JkVHZCb0wzM212WnVWb3hrVExlRERmMiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290377),
(N'VZpWC2y59s6zYNIo1Iuc20FWMDZcuT24u4ci0Iu8', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiR01BdkxnZU1waVU2NXE2eElGd0Q1V21mZmdlOXQ4QjU3Rndmd1ZqVCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290378),
(N'WazCl3kBngqF75KuViei6TEcpQ1PkDSreATjWKlo', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiV0wySENuNnh5RmpxY3ljQlpDeTNRQ0doVkc1aU9FR3FNUWZrY0xPMSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290418),
(N'wDkXornRV9dGT7g3I5b38sjvBABykgaRLTMhM0YH', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiWWJ1N0pjN2hVUmxmaG56U1FKRDdwU0RIMGVGM1ZiRDZ4YzlhcE1sRyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290334),
(N'xq5E4k1EkS6jjntztodjqywqV81vnBiMOZ8uBW5u', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiQ2sxYnA3MWJVS3dIWVZiZ054N1pEMWhvRmFocXJqeUNCWTljVzQ3MyI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290328),
(N'xS7RwJ6jkl3bZAsNbWM9Pz22HSD6WNO9dPRnvIdb', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiQXlwMFUyZUp6bTR2WHJWWDg0VzdRbG5qNHRVckhlMmwzZEN4WVBFMiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NDE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9lbmRvcnNlbWVudHMvY3JlYXRlIjtzOjU6InJvdXRlIjtzOjE5OiJlbmRvcnNlbWVudHMuY3JlYXRlIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1778290421),
(N'ykwkmNDIAjOmHTOHFfApfBSJOptz3juKoq0TplMn', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiSEd1a09QbXZxRVpNdVlSRWg0MlRFMVVOZUFwTXdqUUhxd1dxTTNWNiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290380),
(N'znB1kNya1QWhZENOBtPTbc7dsbYTkqWA1ot8HgiS', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiM1RPSkFxaVZVSnFPcTJqNms3ZkFHU3RKcFViaEZTM01EdHoxYWtvWiI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290416),
(N'ZTUMDJoUsnWAr5FjRy6PmHhmnMwOotl5wJYQ1LF8', NULL, N'127.0.0.1', N'GuzzleHttp/7', N'YTozOntzOjY6Il90b2tlbiI7czo0MDoiTnpDdWtvS2RsQzRTMlFCTWgzb1FMRDlvenJUTXJuakJLcHQ2ekRFOCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7czo1OiJyb3V0ZSI7czoxMDoibG9naW4uZm9ybSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=', 1778290404);

-- ------------------------------------------------------------------
-- Table: [dbo].[user_login_activities]
IF OBJECT_ID(N'dbo.user_login_activities', N'U') IS NOT NULL DROP TABLE [dbo].[user_login_activities];
CREATE TABLE [dbo].[user_login_activities] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [user_id] bigint NULL,
    [username] nvarchar(100) NOT NULL,
    [ip_address] nvarchar(45) NULL,
    [user_agent] nvarchar(255) NULL,
    [success] bit DEFAULT ('0') NOT NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    CONSTRAINT [PK__user_log__3213E83F2328AD99] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[user_login_activities] ON;
INSERT INTO [dbo].[user_login_activities] ([id], [user_id], [username], [ip_address], [user_agent], [success], [created_at], [updated_at]) VALUES
(1, NULL, N'dhedhepratiwi', N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 0, N'2026-04-26 12:03:44.153', N'2026-04-26 12:03:44.153'),
(2, NULL, N'dhedhepratiwi', N'127.0.0.1', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 0, N'2026-04-26 12:03:49.357', N'2026-04-26 12:03:49.357'),
(3, NULL, N'dhedhepratiwi', N'139.0.189.35', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 0, N'2026-04-26 12:06:24.457', N'2026-04-26 12:06:24.457'),
(4, 3, N'dhedhepratiwi', N'139.0.189.35', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 1, N'2026-04-26 12:22:42.777', N'2026-04-26 12:22:42.777'),
(5, 3, N'dhedhepratiwi', N'114.8.199.105', N'Mozilla/5.0 (iPhone; CPU iPhone OS 26_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/147.0.7727.99 Mobile/15E148 Safari/604.1', 1, N'2026-04-27 04:00:22.773', N'2026-04-27 04:00:22.773'),
(6, 3, N'dhedhepratiwi', N'114.8.199.105', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 1, N'2026-04-27 06:08:54.347', N'2026-04-27 06:08:54.347'),
(7, 3, N'dhedhepratiwi', N'202.179.187.36', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 1, N'2026-04-27 07:07:22.917', N'2026-04-27 07:07:22.917'),
(8, 3, N'dhedhepratiwi', N'103.158.195.147', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36', 1, N'2026-04-27 07:17:29.537', N'2026-04-27 07:17:29.537'),
(9, 3, N'dhedhepratiwi', N'139.0.137.108', N'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Mobile/15E148 Safari/604.1', 1, N'2026-04-28 09:53:23.377', N'2026-04-28 09:53:23.377'),
(10, 3, N'dhedhepratiwi', N'139.0.137.108', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36', 1, N'2026-04-28 11:41:32.170', N'2026-04-28 11:41:32.170'),
(11, 3, N'dhedhepratiwi', N'139.194.106.178', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 1, N'2026-05-04 06:28:57.483', N'2026-05-04 06:28:57.483'),
(12, 3, N'dhedhepratiwi', N'139.194.106.178', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36', 1, N'2026-05-04 14:29:50.603', N'2026-05-04 14:29:50.603'),
(13, 3, N'dhedhepratiwi', N'149.113.255.72', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36', 1, N'2026-05-05 12:44:36.320', N'2026-05-05 12:44:36.320'),
(10002, 3, N'dhedhepratiwi', N'157.85.206.78', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36', 1, N'2026-05-08 14:12:21.243', N'2026-05-08 14:12:21.243'),
(10003, 3, N'dhedhepratiwi', N'202.179.187.36', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36', 1, N'2026-05-09 01:34:13.290', N'2026-05-09 01:34:13.290'),
(10004, 3, N'dhedhepratiwi', N'157.85.206.78', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36', 1, N'2026-05-09 03:55:35.247', N'2026-05-09 03:55:35.247'),
(10005, 3, N'dhedhepratiwi', N'157.85.206.78', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-10 04:58:29.647', N'2026-05-10 04:58:29.647'),
(10006, 3, N'dhedhepratiwi', N'157.85.206.78', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-13 12:58:49.287', N'2026-05-13 12:58:49.290'),
(10007, 3, N'dhedhepratiwi', N'114.10.70.116', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-15 02:07:43.070', N'2026-05-15 02:07:43.070'),
(10008, 3, N'dhedhepratiwi', N'114.8.197.4', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-19 11:32:23.333', N'2026-05-19 11:32:23.333'),
(10009, 3, N'dhedhepratiwi', N'114.10.65.235', N'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1', 1, N'2026-05-19 11:51:53.073', N'2026-05-19 11:51:53.073'),
(10010, 3, N'dhedhepratiwi', N'103.3.222.68', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-22 15:14:00.257', N'2026-05-22 15:14:00.257'),
(10011, 3, N'dhedhepratiwi', N'157.85.209.138', N'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36', 1, N'2026-05-24 12:17:44.450', N'2026-05-24 12:17:44.450');
SET IDENTITY_INSERT [dbo].[user_login_activities] OFF;

-- ------------------------------------------------------------------
-- Table: [dbo].[users]
IF OBJECT_ID(N'dbo.users', N'U') IS NOT NULL DROP TABLE [dbo].[users];
CREATE TABLE [dbo].[users] (
    [id] bigint IDENTITY(1,1) NOT NULL,
    [name] nvarchar(255) NOT NULL,
    [email] nvarchar(255) NULL,
    [email_verified_at] datetime NULL,
    [password] nvarchar(255) NOT NULL,
    [remember_token] nvarchar(100) NULL,
    [created_at] datetime NULL,
    [updated_at] datetime NULL,
    [username] nvarchar(255) NOT NULL,
    [role] nvarchar(20) DEFAULT ('trial') NOT NULL,
    [trial_ends_at] date NULL,
    [active] bit DEFAULT ('1') NOT NULL,
    [session_code] nvarchar(80) NULL,
    CONSTRAINT [PK__users__3213E83FD07A1DFA] PRIMARY KEY ([id])
);
SET IDENTITY_INSERT [dbo].[users] ON;
INSERT INTO [dbo].[users] ([id], [name], [email], [email_verified_at], [password], [remember_token], [created_at], [updated_at], [username], [role], [trial_ends_at], [active], [session_code]) VALUES
(3, N'dhedhepratiwi', N'dhedhepratiwi@gmai.com', N'2026-04-26 19:09:13.000', N'$2y$12$875SKyATm5BkAMghjgSore8TOnshhBCadLBfUmxVF3xvVt6BeyP.G', N'giN8q45VOrhvfQRLBAApl73zdHw375mPEX5dVrVuaXlLxm0aSuDwdLkCIXJS', NULL, N'2026-05-24 12:17:44.407', N'dhedhepratiwi', N'master', NULL, 1, N'MHcZnpN3DqqslJVvEqjzlDTXVCgDH1SHowoDn95j'),
(10002, N'Nilo', N'Nilo@trial.local', NULL, N'$2y$12$v6KFRhC2jRyv/yUi5IeHHussrIs97uPsZvRanfctnw27fez0TZexC', NULL, N'2026-05-10 05:01:40.237', N'2026-05-10 05:01:40.237', N'Nilo', N'trial', N'2026-05-11', 1, NULL);
SET IDENTITY_INSERT [dbo].[users] OFF;
